# ktb-bootcampchat-redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ktb-bootcampchat-redis
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: ktb-bootcampchat
    component: redis