# ktb-bootcampchat-mongodb-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ktb-bootcampchat-mongodb-pvc
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
    component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi