# ktb-bootcampchat-mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ktb-bootcampchat-mongodb
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
    component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: ktb-bootcampchat
    component: mongodb