# ktb-bootcampchat-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ktb-bootcampchat-backend
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
    component: backend
spec:
  selector:
    app: ktb-bootcampchat
    component: backend
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 5000
      protocol: TCP
    - name: websocket
      port: 8081
      targetPort: 8081
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800