# ktb-bootcampchat-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktb-bootcampchat-backend
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ktb-bootcampchat
      component: backend
  template:
    metadata:
      labels:
        app: ktb-bootcampchat
        component: backend
    spec:
      containers:
        - name: ktb-bootcampchat-backend
          image: ktb-bootcampchat/backend:latest
          ports:
            - containerPort: 5000
            - containerPort: 8081
              name: websocket
          envFrom:
            - configMapRef:
                name: ktb-bootcampchat-config
            - secretRef:
                name: ktb-bootcampchat-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5