# ktb-bootcampchat-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ktb-bootcampchat-config
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
data:
  # 백엔드 일반 설정
  MONGO_HOST: "ktb-bootcampchat-mongodb"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "bootcampchat"
  REDIS_HOST: "ktb-bootcampchat-redis"
  REDIS_PORT: "6379"
  SERVER_PORT: "5000"

  # 프론트엔드 일반 설정
  NEXT_PUBLIC_API_URL: "http://ktb-bootcampchat-backend:5000"

  # 공통 환경 설정
  NODE_ENV: "production"
  LOG_LEVEL: "info"