- name: Configure Kubernetes master node
  hosts: helm
  become: no
  tasks:
    - name: Add helm charts 
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.repo_url }}"
      loop: "{{ ansible_helm_charts }}"

    - name: Deploy Calico System
      kubernetes.core.helm:
        kubeconfig: "{{ ansible_home_dir }}/.kube/config"
        name: "{{ item.name }}"
        chart_ref: "{{ item.chart_ref }}"
        release_namespace: "{{ item.namespace }}"
        create_namespace: true
      loop:
        - name: projectcalico
          repo_url: https://docs.tigera.io/calico/charts
          chart_ref: projectcalico/tigera-operator
          namespace: tigera-operator

    # - name: Deploy Helm charts
    #   kubernetes.core.helm:
    #     kubeconfig: "{{ ansible_home_dir }}/.kube/config"
    #     name: "{{ item.name }}"
    #     chart_ref: "{{ item.chart_ref }}"
    #     release_namespace: "{{ item.namespace }}"
    #     create_namespace: true
    #   loop: "{{ ansible_helm_charts }}"