# ktb-bootcampchat-zookeeper-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktb-bootcampchat-zookeeper
  namespace: ktb-bootcampchat
  labels:
    app: ktb-bootcampchat
    component: zookeeper
spec:
  replicas: 1  # ZooKeeper는 단일 노드로 운영 (개발 환경)
  selector:
    matchLabels:
      app: ktb-bootcampchat
      component: zookeeper
  template:
    metadata:
      labels:
        app: ktb-bootcampchat
        component: zookeeper
    spec:
      containers:
        - name: ktb-bootcampchat-zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 15
            periodSeconds: 5